const translations = {
  en: {
    overview: 'Overview', mixer: 'Mixer', profiles: 'Profiles', enableForTab: 'Enable for this tab', disableForTab: 'Disable for this tab', gain: 'Gain', compressor: 'Compressor, distortion protection', signalWave: 'Spectral analyzer', tenBandEq: '10-band equalizer', customSettings: 'Custom settings', compression: 'Compression', balance: 'Balance', center: 'center', left: 'left', right: 'right', limiter: 'Limiter, clipping protection', proNote: 'Mixer and advanced settings are available with a PRO subscription.', liveNote: 'Changes apply instantly to the current tab.', getPro: 'Get PRO subscription', siteProfiles: 'Site profiles', defaultProfile: 'Default profile', saveSiteSettings: 'Save site settings', quickFeatures: 'Quick features', hotkeys: 'Keyboard shortcuts', hotkeysHint: 'Use these shortcuts while browsing:', toggleShortcut: 'Toggle audio processing', gainUpShortcut: 'Increase gain by 10%', gainDownShortcut: 'Decrease gain by 10%', localSettings: 'Settings are stored locally. Cross-device sync can be added with an account.', language: 'Language', default: 'default', currentTab: 'Current tab', starting: 'Starting capture...', stopping: 'Stopping capture...', startError: 'Could not start capture', checkoutMissing: 'Payment link is not connected yet.', checkoutOpening: 'Opening checkout...', saved: 'Profile saved for', db: 'dB', presets: { custom: 'Custom settings', voice: 'Clear voice', music: 'Music', bass: 'Bass', deepBass: 'Deep bass', podcast: 'Podcast', movie: 'Movie', gaming: 'Gaming', details: 'Details', warm: 'Warm sound', night: 'Night mode' }
  },
  ru: {
    overview: 'Обзор', mixer: 'Микшер', profiles: 'Профили', enableForTab: 'Включить для этой вкладки', disableForTab: 'Отключить для этой вкладки', gain: 'Усиление', compressor: 'Компрессор, защита от искажений', signalWave: 'Спектральный анализатор', tenBandEq: '10-полосный эквалайзер', customSettings: 'Ручная настройка', compression: 'Компрессия', balance: 'Баланс', center: 'центр', left: 'лево', right: 'право', limiter: 'Лимитер, защита от клиппинга', proNote: 'Микшер и расширенные настройки доступны в PRO-подписке.', liveNote: 'Изменения применяются сразу к текущей вкладке.', getPro: 'Оформить PRO-подписку', siteProfiles: 'Профили сайтов', defaultProfile: 'Стандартный профиль', saveSiteSettings: 'Сохранить настройки сайта', quickFeatures: 'Быстрые функции', hotkeys: 'Горячие клавиши', hotkeysHint: 'Используйте эти сочетания во время просмотра:', toggleShortcut: 'Включить или отключить обработку звука', gainUpShortcut: 'Увеличить усиление на 10%', gainDownShortcut: 'Уменьшить усиление на 10%', localSettings: 'Настройки хранятся локально. Синхронизация между устройствами доступна с аккаунтом.', language: 'Язык', default: 'стандартный', currentTab: 'Текущая вкладка', starting: 'Запускаю захват...', stopping: 'Отключаю захват...', startError: 'Не удалось запустить захват', checkoutMissing: 'Ссылка на оплату ещё не подключена.', checkoutOpening: 'Открываю страницу оплаты...', saved: 'Профиль сохранён для', db: 'дБ', presets: { custom: 'Ручная настройка', voice: 'Чёткий голос', music: 'Музыка', bass: 'Бас', deepBass: 'Глубокий бас', podcast: 'Подкаст', movie: 'Кино', gaming: 'Игры', details: 'Детали', warm: 'Тёплый звук', night: 'Ночной режим' }
  }
};

let language = 'en';

function text(key) {
  return translations[language][key] || key;
}
